name: Health check for EC2 and Market data notification
on:
  schedule:
    - cron: '5,15,25,35,45,55 13-20 * * 1-5' # weekdays
    - cron: '5,15,25,35,45,55 2-14 * * 0,6' # weekends, 0 = sunday
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'info' 
        type: choice
        options:
        - info
        - warning
        - debug
env:
  HOST_NAME: ${{ secrets.HOST_NAME }}
jobs:
  ec2_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if EC2 is running
        run: |
          curl $HOST_NAME
  notify_unsuccessful_ec2_health_check:
    runs-on: ubuntu-latest
    needs: [ec2_health_check]
    if: ${{ failure() }}
    steps:
      - name: Send telegram notification EC2 is not running
        env:
          TELEGRAM_DEV_BOT_TOKEN: ${{ secrets.TELEGRAM_DEV_BOT_TOKEN }}
          TELEGRAM_DEV_ID: ${{ secrets.TELEGRAM_DEV_ID }}
        run: |
          now=$(date +%Y-%m-%dT%H:%M:%S)
          text=$(echo "\[Github action\] Market data notification infra: Health check for $HOST_NAME failed at $now. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" | sed 's~[[:blank:]]~%20~g')
          curl "https://api.telegram.org/bot${TELEGRAM_DEV_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_DEV_ID}&text=$text"
  market_data_notification_health_check:
    runs-on: ubuntu-latest
    needs: [ec2_health_check]
    steps:
      - name: Configure basic tools
        run: |
          sudo apt-get -y install jq
      - name: Check if Market data notification is running
        run: |
          curl $HOST_NAME/healthz
          if [ $? -ne 0 ]
          then
            now=$(date +%Y-%m-%dT%H:%M:%S)
            text=$(echo "\[Github action\] Market data notification infra: Health check for $HOST_NAME/healthz failed at $now. Workflow: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" | sed 's~[[:blank:]]~%20~g')
            curl "https://api.telegram.org/bot${TELEGRAM_DEV_BOT_TOKEN}/sendMessage?chat_id=${TELEGRAM_DEV_ID}&text=$text"
            exit 1
          fi 
          
      
      